[tox]
envlist = py314

[testenv]
setenv =
    PYTHONDONTWRITEBYTECODE=1
runner = uv-venv-lock-runner
commands =
    uv run py.test --cov relduty_deployer --cov-report term-missing tests

[testenv:check]
runner = uv-venv-lock-runner
commands =
    uv run ruff check {toxinidir}
    uv run ruff format --check {toxinidir}
    uv lock --check

[coverage:run]
branch = true
